### PR TITLE
Re-add session errors (preparation for merge)

### PR DESCRIPTION
**Pull request by timriley**
I've taken @tak1n's work in #379, done another rebase, and made a few tidies in anticipation of merging this. 

I agree with @tak1n in his original PR that there might be better implementations we could find if we searched for them, but I think this gets the job done, and it does so in a way that doesn't commit us to this particular implementation either, everything done here is internal and we can always revisit this in the future.

And what's most important here is that we give helpful feedback to the user at a time when they may need it.

### CODE REVIEW

**Comment by timriley** [comment]
[Re-add helpful errors when session is accessed off response, but sessions are not enabled](https://trello.com/c/MJtJHbcC/104-re-add-helpful-errors-when-session-is-accessed-off-response-but-sessions-are-not-enabled)

**Comment by timriley** [comment]
[Re-add helpful errors when session is accessed off response, but sessions are not enabled](https://trello.com/c/MJtJHbcC/104-re-add-helpful-errors-when-session-is-accessed-off-response-but-sessions-are-not-enabled)

**Comment by timriley** [comment]
[Re-add helpful errors when session is accessed off response, but sessions are not enabled](https://trello.com/c/MJtJHbcC/104-re-add-helpful-errors-when-session-is-accessed-off-response-but-sessions-are-not-enabled)

**Comment by timriley** [comment]
[Re-add helpful errors when session is accessed off response, but sessions are not enabled](https://trello.com/c/MJtJHbcC/104-re-add-helpful-errors-when-session-is-accessed-off-response-but-sessions-are-not-enabled)

**Review by solnic — APPROVED** [review]

**Review by tak1n — APPROVED** [review]

**Pull request merged**
