### PR TITLE
Add read only flash & session on request object

### PR DESCRIPTION
**Pull request by tak1n**
Branched off from the work at https://github.com/hanami/controller/pull/379

### CODE REVIEW

**Comment by tak1n** [comment]
[Add read-only flash and session objects to Request, rationalize Request/Response overall](https://trello.com/c/LSi57W0a/81-add-read-only-flash-and-session-objects-to-request-rationalize-request-response-overall)

**Comment by jodosha** [comment]
@tak1n I'm not 100% sure about the implementation of #379.

Is it possible to decouple the two enhancements?
Specifically, could you please branch this PR from `main`?

**Comment by timriley** [comment]
FYI, see #398 for a cleaner diff over the main branch.

**Comment by timriley** [comment]
@tak1n Thank you so much for your work here! It was just what we needed to come up with a good working approach for 2.0; see #399 for how we'll handle this :)

**Pull request closed without merging**
