### PR TITLE
Update hanami utils and use #deep_symbolize!

### PR DESCRIPTION
**Pull request by AlfonsoUceda**
Related to https://github.com/hanami/utils/pull/162

### CODE REVIEW

**Comment by AlfonsoUceda** [comment]
cc @alexd16

**Comment by beauby** [comment]
For the record, what's the rationale behind symbolizing everything? In every case I can think of, it feels like a waste of CPU for little gains in code clarity.

**Comment by AlfonsoUceda** [comment]
cc @jodosha

**Comment by cllns** [comment]
@beauby I like symbolizing everything. It's almost like having indifferent access, without all the complexity. It provides a more consistent interface, letting you abstract over the implementation detail of whether the input hash uses strings or symbols for keys.

Also, I think the CPU cycles are negligible? I could be wrong though.

**Comment by jodosha** [comment]
@beauby It's true, the implementation is not efficient.

But each design comes with a tradeoff. In this case what we value the most is the API: provide symbol-only access. Then we can work to make it to perform better.

**Pull request merged**
