### PR TITLE
reduce memory usage with freezing mime types

### PR DESCRIPTION
**Pull request by railsme**

### CODE REVIEW

**Comment by joneslee85** [comment]
@railsme the test fails, can you please investigate?

**Comment by railsme** [comment]
@joneslee85 Fail is not related to my changes, but I'll try to figure out what's the problem.
Possible to reproduce on master branch with seed from CI.

```
bundle exec rake test:coverage --trace TESTOPTS="--seed=17724"
```

**Comment by jodosha** [comment]
@railsme Hey thanks for this PR. How did you have measured the memory usage? What's the gain? Thank you.

**Comment by railsme** [comment]
@jodosha I used rack-mini-profiler to see memory usage on http request. I can provide you a configuration and screenshots(or copy-paste) if you want to see it :smile_cat:

**Comment by jodosha** [comment]
@railsme That would be great. Thank you! How much memory is saved with this patch?

**Comment by railsme** [comment]
@jodosha don't know if 9792 bytes is good save for request :laughing:

**Comment by joneslee85** [comment]
@railsme would you be able to provide us the profiling report?

**Comment by jodosha** [comment]
@railsme Okay, this looks good, thank you! :+1:

**Pull request merged**
