### PR TITLE
Makes errors in session.rb public in order to be testable 

### LINKED ISSUE #147: NoMethodError: private method `errors' called for action
Reported by @nickmorlan in chat.

The problem is caused by `session.rb`, that defines `errors` as a private method.

Here's a stack trace:
https://gist.github.com/nickmorlan/4ce60b1632f115152289

### PR DESCRIPTION
**Pull request by vasspilka**
Fixes #147

### CODE REVIEW

**Comment by jodosha** [comment]
@vasspilka Hello and thanks for this fix. Before to merge this PR, we need to add a test. The test will prove that the patch solves the problem **and** it will prevent this issue to come back again (regression).

Would you consider to add enhance this test case? https://github.com/hanami/controller/blob/master/test/method_visibility_test.rb

Thanks.

**Comment by vasspilka** [comment]
Will this do?

**Comment by cllns** [comment]
Hey @vasspilka, I think the test might be better in `test/session_test.rb`. What do you think?

Also, rather than testing to see if the public method exists, what about testing the return value of that method?
Similar to what is done in [`test/action_test.rb`](https://github.com/hanami/controller/blob/7e45605903beba8a30e9499cf1b8ceea4f74c88f/test/action_test.rb#L33-L39) (you might have to add some params validation to `SessionAction` in `test/fixtures.rb` in order to get an error?)

**Comment by vasspilka** [comment]
It returns an empty array when everything is ok, should I create a new `@action` and then check if its `#error` are `#empty?` ?

**Comment by cllns** [comment]
@vasspilka I think adding an actual error to the session is best, to ensure it's getting passed through. Otherwise, the `errors` method might be coming from just `Action`, not `Action::Sessions`

**Comment by jodosha** [comment]
@vasspilka I just merged this, thanks!

**Pull request merged**
